{% set name = "pmx" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 323dd5091c62255f1f6cbfc6b4869ef9672a188ce7e3439ed1bb6e9cf2c3804c

build:
  number: 0
  entry_points:
    - pmx = pmx.scripts.cli:entry_point
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - matplotlib >=2.2
    - numpy >=1.14
    - pip
    - python
    - scipy >=1.1
  run:
    - matplotlib >=2.2
    - numpy >=1.14
    - python
    - scipy >=1.1

test:
  imports:
    - pmx
  commands:
    - pmx --help

about:
  home: https://github.com/deGrootLab/pmx
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file:
  summary: Python Toolbox structure file editing and writing simulation setup/analysis tools
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - matteoaldeghi
