travis:
  secure:
    BINSTAR_TOKEN: BB/7Sd911l4u2LgiSpzY3Th70yfZg8y5gGdtJ1Rk5LrUgoTWyy28/1/iTtG2MFtw18HCllMB9MZIThl8Cbjbmcwh/flT3qIu1MWdyWlkjZb+dEooQettLfRAFSfkGOUwazEcVsdg9g8A1OzsNxfjiJg+4kwFRddtKK3gn6gzXogAr0EoJIBd5PuVh10IGUJ/XyakTf5gxMWNk1beIqY+9X80IkjpngE/YIvgCsXHPLR0s4cdlo2EkCeWV4A46C51qY2Dzyf7ogUFwiy/vTcQOkI0Szti3iV52T23bqGbLYpoBtOeqCMZRWvr1nAGQVFZXNe4XSiYjkDw0xWMC1H9gOR7p4ZF2adeCLkKacErlKocpbfbZWQlEYzCnB/tN8FC6hThtwYTJ68gjR+mQw6mk9V/P/JcEUZIN9MXmFqJTBQQZCXMy/MKymQ8x2/Rm9+Mq1URQnq4VJrGztJJQ2xvTm8n+0uNxavgLfpgv092DgDEeLVqVBKYu4efIW7rhhxRq4RFVbSXxi6iqmccJzUtKhbyAANEPOrKaqa+g4Y4d9z2l3UWcl7RGwkPQuIrb2qpa2eIDpUsZOeDu/AM7bE8o1KiFDV2tu8UyPCJTRdeTUmvSTDTLA5nM4/BHHrIDs69f9hqAGItxQfFo7FiD5evzYgegqiAjCc+GUXd3jixFD4=
appveyor:
  secure:
    BINSTAR_TOKEN: X84oueAaVX4SbY1S3PJoqYea1dMFg+snh+a5yY8se+/qYVcxMyksGQIv2WpLyZLN
